/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ML96' at '04/02/16 13:37' with Gradle 2.10
 *
 * @author ML96, @date 04/02/16 13:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
